version: "3.9"

services:
  app:
    image: availability-tracker:latest   # image built in ci.sh
    container_name: availability-tracker
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-net
    
  redis:
    image: redis:7-alpine
    container_name: availability-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-net
  
volumes:
  redis-data:

networks:
  app-net:
    driver: bridge
